config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get 'up' => 'rails/health#show', as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
  root 'title#index'

  get 'question', to: 'question#index'

  get 'question_state', to: 'question_state#index'
  get 'question_state/first_topic'
  get 'question_state/next_topic'
  get 'question_state/next_question'

  get 'question_state/previous_topic'
  get 'question_state/previous_question'
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/question_controller.rb
class QuestionController < ApplicationController
  def index
    @question = Question.new
  end
end

app/controllers/question_state_controller.rb
class QuestionStateController < ApplicationController
  before_action :set_question_state

  def index
    set_vars
    render :common
  end

  def first_topic
    @question_state.first_topic
    update_channel_and_redirect
  end

  def next_topic
    if Question.exist?(@question_state.topic + 1, 1)
      @question_state.next_topic
    else
      @question_state.topic = Question::COMPLETED_VALUE
      @question_state.question = Question::COMPLETED_VALUE
    end
    update_channel_and_redirect
  end

  def previous_topic
    if @question_state.topic > 1
      @question_state.topic = Question.previous_topic_of(@question_state.topic)
      @question_state.question = Question.last_question_of(@question_state.topic)
    end
    update_channel_and_redirect
  end

  def next_question
    if Question.exist?(@question_state.topic, @question_state.question + 1)
      @question_state.next_question
    elsif Question.exist?(@question_state.topic + 1, 1)
      @question_state.next_topic
    else
      @question_state.topic = Question::COMPLETED_VALUE
      @question_state.question = Question::COMPLETED_VALUE
    end
    update_channel_and_redirect
  end

  def previous_question
    if @question_state.topic == Question::COMPLETED_VALUE
      @question_state.topic = Question.previous_topic_of(@question_state.topic)
      @question_state.question = Question.last_question_of(@question_state.topic)
    elsif @question_state.question > 1 && Question.exist?(@question_state.topic, @question_state.question - 1)
      @question_state.question -= 1
    elsif @question_state.topic > 1
      @question_state.topic -= 1
      @question_state.question = Question.last_question_of(@question_state.topic)
    else
      @question_state.topic = 1
      @question_state.question = 1
    end
    update_channel_and_redirect
  end

  private

  def set_question_state
    @question_state = Rails.application.config.question_state
  end

  def set_vars
    @question = Question.new
    @next_topic, @next_question = @question.next_topic_and_question
  end

  def update_channel_and_redirect
    ActionCable.server.broadcast("question_details", { topic: @question_state.topic, question: @question_state.question, completed_value: Question::COMPLETED_VALUE })
    if ENV.fetch('USE_HTTP_REDIRECT', '0') == '1'
      redirect_to action: :index, protocol: 'http://'
    else
      redirect_to action: :index
    end
  end
end

app/controllers/title_controller.rb
class TitleController < ApplicationController
  def index; end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def escape(text)
    raw h(text).splitlines.join('<br/>')
  end
end

app/helpers/question_helper.rb
module QuestionHelper
end

app/helpers/question_state_helper.rb
module QuestionStateHelper
end

app/helpers/title_helper.rb
module TitleHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>QAndA</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body class="min-vh-100">
  <div class="min-vh-100">
  <div class="container content min-vh-100">
    <%= yield %>
  </div></div>
  </body>
</html>

app/views/question/_index.html.erb
<table class="table table-striped" style="max-width: 300px">
  <thead>
  <tr>
    <th>&nbsp;</th>
    <th>Topic</th>
    <th>Question</th>
  </tr>
  </thead>
  <tbody></tbody>
  <tr>
    <th>Current</th>
    <td><%= @question.topic %></td>
    <td><%= @question.question %></td>
  </tr>
  <tr>
    <th>On Server</th>
    <td id="dynTopic"><%= @question.topic %></td>
    <td id="dynQuestion"><%= @question.question %></td>
  </tr>
</table>

<hr style="margin-bottom: 20px; margin-top: 5px;" />

<pre class="the-question">
<%= escape @question.text %>
</pre>

app/views/question/index.html.erb
<% if @question.topic != Question::COMPLETED_VALUE %>
<%= render partial: 'index' %>
<%else %>
  <h1>Completed</h1>
<%end %>

app/views/question_state/_next_buttons.html.erb
<div class="row">
  <div class="col col-sm-6">
    <div class="row gap-3">
      <div class="col px-3">
        <form action="<%= question_state_next_question_path %>">
          <button type="submit" class="btn btn-primary"
                  <%- if @question_state.topic == Question::COMPLETED_VALUE %> disabled
                  <%- end %>>Next question
          </button>
        </form>
      </div>
    </div>
    <div class="row gap-3">
      <div class="col px-3">
        <form action="<%= question_state_previous_question_path %>">
          <button type="submit" class="btn btn-primary"
                  <%- if @question_state.topic == Question::COMPLETED_VALUE || (@question_state.topic == 1 && @question_state.question == 1) %>
                  disabled
                  <%- end %>>Previous question
          </button>
        </form>
      </div>
    </div>
  </div>
  <div class="col col-sm-4">
    <div class="row gap-3">
      <div class="col px-3">
        <form action="<%= question_state_next_topic_path %>">
          <button type="submit" class="btn btn-secondary"
                  <%- if @question_state.topic == Question::COMPLETED_VALUE  %> disabled
                  <%- end %>>Next topic
          </button>
        </form>
      </div>
    </div>

    <div class="row">
      <div class="col px-3">
        <form action="<%= question_state_previous_topic_path %>">
          <button type="submit" class="btn btn-secondary"
                  <%- if @question_state.topic == 1 %>  disabled
                  <%- end %>>Previous topic
          </button>
        </form>
      </div>
    </div>
    <div class="row">
      <div class="col px-3">
        <form action="<%= question_state_first_topic_path %>">
          <button type="submit" class="btn btn-danger">First topic (RESET)</button>
        </form>
      </div>
    </div>
  </div>
</div>

app/views/question_state/_state.html.erb
<h1>Question state</h1>

<h2>Topic and Question Numbers</h2>
<table class="table table-striped" style="max-width: 300px">
  <thead>
  <tr>
    <th>&nbsp;</th>
    <th>Topic</th>
    <th>Question</th>
  </tr>
  </thead>
  <tbody></tbody>
  <tr>
    <th>Current</th>
    <% if @question.topic != Question::COMPLETED_VALUE %>
      <td><%= @question_state.topic %></td>
      <td><%= @question_state.question %></td>
    <% else %>
      <td colspan="2">
        <div class="completed">Completed</div>
      </td>
    <% end %>
  </tr>
  <tr>
    <th>Next</th>
    <% if @question.topic != Question::COMPLETED_VALUE %>
      <% if @next_topic != Question::COMPLETED_VALUE %>
        <td><%= @next_topic %></td>
        <td><%= @next_question %></td>
      <% else %>
        <td colspan="2">
          <div class="completed">Completed</div>
        </td>
      <% end %>
    <% else %>
      <td colspan="2">
        <div class="completed">Nothing</div>
      </td>
    <% end %>
  </tr>
  <tr>
    <th>On Server</th>
    <td id="dynTopic"><%= @question.topic != Question::COMPLETED_VALUE ? @question.topic : 'Completed' %></td>
    <td id="dynQuestion"><%= @question.question != Question::COMPLETED_VALUE ? @question.question : 'Completed' %></td>
  </tr>
</table>

<hr>
<h2>Actions</h2>
<%= render partial: 'next_buttons' %>

app/views/question_state/common.html.erb
<%= render partial: 'state' %>
<hr/>
<h2>Current Question</h2><br />
<pre class="pre-question"><%= @question.text %></pre>
<hr/>
<h2>Current Answer</h2><br />
<pre class="pre-answer"><%= @question.answer %></pre>

app/views/question_state/first_topic.html.erb
<%= render partial: 'state' %>

app/views/title/index.html.erb
<h1>Hello</h1>
<p>To start, visit <a href="<%= question_path %>">first question</a></p>